### ISSUE TITLE
Deployment to Play store + F-droid for Android

### ISSUE THREAD

**Issue by Poussinou** [darekaze/canorous#12]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by darekaze** [comment]
Hey there @Poussinou,

I have planned to revisit this app some days in September 2019 for an upgrade and reorganize the existing code cause during these months I've learned a lot about managing a project.. and I've found out the current code is quite a mess and hard to manage, and of course the current UI/UX still needs to be enhanced..

Apologize for the inactive in this cool project, and yes I've considered to deploy to play store as well as fdroid, but currently the app still needs some works before releasing to the stores. 

Of course I welcome anyone to work on this project by making PRs and make this app better

**Comment by darekaze** [comment]
This project will be restart in September and I'll be working on it during my free time (day off). Thanks for supporting the project

**Comment by Poussinou** [comment]
So let's wait a little bit to deploy the app 👍
