### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [darekaze/canorous#9]
Hi @darekaze 

I am a logo designer and I am contributing to open source projects that do not have a logo. So I wanted to design a logo for this repo. I hope we create a logo together. I'll wait for your feedback.Have a 
![1](https://user-images.githubusercontent.com/36298335/56985795-d5a06780-6b91-11e9-87ee-d6b02eeb608b.jpg)
nice day!

**Comment by darekaze** [comment]
Hi @reallinfo ! First of all, Thank you for the design. I like the concepts and design of the logo.

After discuss with @ZXYCharles , there are some changes we would like to address:
1. Since our app color theme is based on Colors.red[500] and white ([check here](https://docs.flutter.io/flutter/material/Colors-class.html)), can you change the icon color theme to fit the app?
2. We think that the sharing part of the logo should be a bit smaller or thinner than the musical note, and the nodes on the sharing part can be smaller.

Thanks

**Comment by reallinfo** [comment]
Hi again @darekaze I made the changes you wanted. how does it look?

**Comment by darekaze** [comment]
Hi @reallinfo 😃 

The shape looks good to me, I think it's a bit plain in color compared to the previous one..
Could you consider to add another color (or maybe 2 more) to the current color scheme? (I leave the decision to you)

By the way, can I know the font family you've used for the design?

Thanks

**Comment by reallinfo** [comment]
Sure, I have tried a few variations according to the color scheme. 

![can](https://user-images.githubusercontent.com/36298335/57066170-261fde00-6cd4-11e9-96cd-2108e0de8a34.jpg)

**Comment by darekaze** [comment]
Hi @reallinfo :wave:

The 2nd one looks good (counting from the top) and i think it can be the banner of this project.

For the application logo, I'm thinking of making the logo background color `Colors.red[500]` and the actual logo white, what do you think?

Some references of the logo design idea can be found [here](https://itunes.apple.com/us/app/soundcloud-music-audio/id336353151?mt=8) and [here](https://itunes.apple.com/us/app/whatsapp-messenger/id310633997?mt=8)

Thanks

**Comment by reallinfo** [comment]
yeah, white is a very good choice. You can look at different size variations. I think she looks fine. I think all the variations you want are available below. 

![1](https://user-images.githubusercontent.com/36298335/57128851-626b4100-6d9d-11e9-91ff-35e5d67bee2f.jpg)

**Comment by darekaze** [comment]
I think the logo is ready, @reallinfo . Go ahead to fork and do a pull request.
Have a good weekends! 😆

**Comment by darekaze** [comment]
@reallinfo If you have Android Studio installed, just go ahead to use the provided tools to generate the logo (see [here](https://stackoverflow.com/a/55054303)). 

Or if this is too cumbersome for you, you can create an directory call `assets` and place the material as well as the cc license inside. I will handle the rest with @EvilCharles 

Thanks

**Comment by reallinfo** [comment]
oh okay I'll send a pr soon :) because i'm not good about android studio.

**Comment by reallinfo** [comment]
I sent a pr. Please check it.

https://github.com/darekaze/canorous/pull/11

**Comment by darekaze** [comment]
Merged! (backlog - #11)

**Comment by reallinfo** [comment]
Thanks! Feel free to contact me if you need any help.
